"""new column added in user table

Revision ID: 1128b8cc9a3d
Revises: 187855982332
Create Date: 2024-10-23 18:47:42.217492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1128b8cc9a3d'
down_revision: Union[str, None] = '187855982332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Handle 'asset' table foreign key creation with a name for the constraint
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_asset_user_id', 'user', ['user_id'], ['id'])  # Added a name for the foreign key

    # Handle 'config' table alteration
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.alter_column('value',
                              existing_type=sa.VARCHAR(),
                              nullable=True)

    # Handle 'cred' table alteration
    with op.batch_alter_table('cred', schema=None) as batch_op:
        batch_op.alter_column('transports',
                              existing_type=sa.VARCHAR(),
                              nullable=False)

    # Handle 'persona' table alterations
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.alter_column('voice_id',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.alter_column('face_id',
                              existing_type=sa.VARCHAR(),
                              nullable=True)

    # Handle 'user' table alterations and additions
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailVerified', sa.Boolean(), nullable=False))
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(),
                              nullable=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'emailVerified')
    op.alter_column('persona', 'face_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('persona', 'voice_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('persona', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cred', 'transports',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('config', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'asset', type_='foreignkey')
    # ### end Alembic commands ###
