"""auth_new_3

Revision ID: 5631e5648f84
Revises: eb581aff409c
Create Date: 2024-08-04 19:36:50.749829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5631e5648f84'
down_revision: Union[str, None] = 'eb581aff409c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passkey_user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_key_cred',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('passkey_user_id', sa.String(), nullable=False),
    sa.Column('backed_up', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('transports', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['passkey_user_id'], ['user.passkey_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_key_cred', type_='foreignkey')
    op.create_foreign_key(None, 'public_key_cred', 'user', ['passkey_user_id'], ['id'])
    # ### end Alembic commands ###
