"""added page table

Revision ID: c189fb6eda90
Revises: dcaf2be4345d
Create Date: 2024-09-26 14:36:50.706957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c189fb6eda90'
down_revision: Union[str, None] = 'dcaf2be4345d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   op.create_table('page',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),    
    sa.Column('assistant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),    
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
