"""added conversation table
 
Revision ID: d34acf83524e
Revises: 54bbca89da7b
Create Date: 2024-07-30 13:46:03.728078
 
"""
from typing import Sequence, Union
 
from alembic import op
import sqlalchemy as sa
import sqlmodel
 
 
# revision identifiers, used by Alembic.
revision: str = 'd34acf83524e'
down_revision: Union[str, None] = '54bbca89da7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated_timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archive', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assistant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    # ### end Alembic commands ###