"""remove role from user table

Revision ID: e7cfcff87b8e
Revises: 008645bff529
Create Date: 2024-12-23 18:37:01.454972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7cfcff87b8e'
down_revision: Union[str, None] = '008645bff529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
